[phases.setup]
aptPkgs = ["php-gd", "libzip-dev", "unzip", "git"]

[phases.install]
commands = [
  "composer install --ignore-platform-reqs --no-interaction"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"